### PR TITLE
Add parameters inside FeignClient

### LINKED ISSUE #6: Extending struct to use struct fields
Hi,
I was wondering how difficult it would be to enable templates like `#[get("https://api.github.com/repos/{self.path}")]`.
This can be useful to not store URL's as const like the GITHUB example.

My usecase would be a bit more advanced, where a struct stores AUTH JWT's and adds the JWT as a header, which is stored in self.

What are your thoughts?

### PR DESCRIPTION
**Pull request by ajuvercr**
Add parameters inside struct types to handle dynamic URL's betters, example:
```rust
#[derive(Feign)]
#[feign(headers = "Accept: {accept}")]
struct Github {
    #[feign_path("owner")]
    user: &'static str,
    #[feign_path]
    repo: &'static str,
    #[param]
    accept: &'static str,
}

#[feign(url = "https://api.github.com/repos/{owner}/{repo}")]
impl Github {
    #[get]
    async fn home(&self) -> feignhttp::Result<String> {}

    #[get("/repos/{owner}/{repo}", headers = "accept: application/json")]
    async fn repository(&self) -> feignhttp::Result<String> {}
}
```

This makes it easier to have a `Github` instance that always sends requests with the same headers to the same dynamic URL.

Fixes #6.

Changed: 
- Add FeignClient trait + Derive
- Add #[path] #[query] #[param] #[header] parameters inside FeignClients

PS: The code is not the greatest and new tests are missing, but if you feel like merging this PR I can easily add those.

### CODE REVIEW

**Comment by dxx** [comment]
Hi,
That's a very good idea to use structures to store some dynamic data.

About the multipart body, i think it should be universal regardless of which client you use, but the multipart body is implemented when the `reqwest` client is used in this PR. I have considered multipart body before but it makes the library a hassle to develop.

I forgot to set the default branch, would you like to submit a merge request to dev branch?

**Comment by ajuvercr** [comment]
Yeah I failed to implement multipart too for isahc, I tried it with https://github.com/ferristseng/rust-multipart-rfc7578.
As you mentioned it probably needs a rather large rewrite.

I can remove that commit if you want to, but for my use case I really need multi-part support, and I'm more than happy with only using reqwest.

**Comment by dxx** [comment]
I want to remove multipart, when we have a universal solution, we can implement it.

In your example, the `feign` attribute tag above structure is repeated. It can be replaced, example:

```rust
#[derive(Feign)]
// #[feign(headers = "Accept: {accept}")]
struct Github {
    #[feign_path("owner")]
    user: &'static str,
    #[feign_path]
    repo: &'static str,
    #[param]
    accept: &'static str,
}

#[feign(url = "https://api.github.com", headers = "Accept: {accept}")]
impl Github {
    #[get]
    async fn home(&self) -> feignhttp::Result<String> {}

    #[get("/repos/{owner}/{repo}", headers = "accept: application/json")]
    async fn repository(&self) -> feignhttp::Result<String> {}
}
```

So I want to remove it, what do you think?

The `feign_path` is not a good name, how about `url_path`?

**Comment by ajuvercr** [comment]
Hi, I made the requested changes about `url_path` etc, added a test and removed the multipart commit.
Hopefully code quality is as expected too, if not, give me a comment.

**Comment by dxx** [comment]
I had remove some code and fixed some bugs:

- https://github.com/dxx/feignhttp/commit/fe913cc94788004e7754d05278e497e9556b6c70
- https://github.com/dxx/feignhttp/commit/66f5afdbc8ec0a6d5bd9cf2bd2a418099b6bfba8
- https://github.com/dxx/feignhttp/commit/7f4c33173aed7508ac3afbae25de32f87099b6fa

**Comment by dxx** [comment]
The new feature has been released in [v0.5.0](https://github.com/dxx/feignhttp/releases/tag/v0.5.0) .

**Comment by dxx** [comment]
> Yeah I failed to implement multipart too for isahc, I tried it with https://github.com/ferristseng/rust-multipart-rfc7578. As you mentioned it probably needs a rather large rewrite.
> 
> I can remove that commit if you want to, but for my use case I really need multi-part support, and I'm more than happy with only using reqwest.

@ajuvercr Hi, i have released version 0.6.0, which supports multipart forms. I have implemented it for every HTTP backend.

Usage:
- [multipart](https://docs.rs/feignhttp/0.6.0/feignhttp/#multipart)

Implements:
- [multipart.rs](https://github.com/dxx/feignhttp/blob/HEAD/src/multipart.rs)
- [reqwest/http.rs](https://github.com/dxx/feignhttp/blob/HEAD/src/reqwest/http.rs)
- [isahc/http.rs](https://github.com/dxx/feignhttp/blob/HEAD/src/isahc/http.rs)

**Pull request merged**
